"""Initial schema

Revision ID: 356ca67d7eba
Revises:
Create Date: 2025-10-01 17:47:47.833993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types import GUID


# revision identifiers, used by Alembic.
revision: str = '356ca67d7eba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('parameter_size', sa.String(length=20), nullable=True),
    sa.Column('quantization', sa.String(length=20), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pull_progress', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('digest', sa.String(length=128), nullable=True),
    sa.Column('usage_count', sa.BigInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_last_used', 'model_registry', ['last_used'], unique=False)
    op.create_index('idx_model_status', 'model_registry', ['status'], unique=False)
    op.create_index(op.f('ix_model_registry_created_at'), 'model_registry', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_registry_name'), 'model_registry', ['name'], unique=True)
    op.create_table('setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_setting_category'), 'setting', ['category'], unique=False)
    op.create_table('translation_job',
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('source_lang', sa.String(length=20), nullable=False),
    sa.Column('target_langs', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_phase', sa.String(length=16), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_trace', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('result_paths', sa.Text(), nullable=True),
    sa.Column('writeback_mode', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('job_metadata', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_celery_task', 'translation_job', ['celery_task_id'], unique=False)
    op.create_index('idx_job_item_id', 'translation_job', ['item_id'], unique=False)
    op.create_index('idx_job_status_created', 'translation_job', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_translation_job_celery_task_id'), 'translation_job', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_translation_job_created_at'), 'translation_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_translation_job_item_id'), 'translation_job', ['item_id'], unique=False)
    op.create_index(op.f('ix_translation_job_status'), 'translation_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_job_status'), table_name='translation_job')
    op.drop_index(op.f('ix_translation_job_item_id'), table_name='translation_job')
    op.drop_index(op.f('ix_translation_job_created_at'), table_name='translation_job')
    op.drop_index(op.f('ix_translation_job_celery_task_id'), table_name='translation_job')
    op.drop_index('idx_job_status_created', table_name='translation_job')
    op.drop_index('idx_job_item_id', table_name='translation_job')
    op.drop_index('idx_job_celery_task', table_name='translation_job')
    op.drop_table('translation_job')
    op.drop_index(op.f('ix_setting_category'), table_name='setting')
    op.drop_table('setting')
    op.drop_index(op.f('ix_model_registry_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_created_at'), table_name='model_registry')
    op.drop_index('idx_model_status', table_name='model_registry')
    op.drop_index('idx_model_last_used', table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
